import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import React from "react";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={inter.className}>


        <main className="flex min-h-screen flex-col items-center justify-between">
            <div className="w-full max-w-4xl mx-auto">
                <div className="bg-sky-600 min-h-screen px-8 pt-5">
                    {children}
                </div>
            </div>
        </main>
        </body>
        </html>
    );
}
